[package]
name = "backlog_breakdown"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
bevy = "0.12"
bevy_mod_picking = "0.17.0"
bevy_rand = { version = "0.4.0", features = ["rand_chacha"] }
bevy_vector_shapes = "0.6.0"
rand_core = "0.6.4"
